#!/usr/bin/env bash
echo "*******************************"
echo   "Running git pre-push hook"
echo "*******************************"
OUTPUT="/tmp/pre-push-check-$(date +%s)"
./gradlew testGmsDebugUnitTest > $OUTPUT
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
  cat $OUTPUT
  rm $OUTPUT
  echo "***********************************************"
  echo "      Please fix tests before pushing "
  echo "***********************************************"
  exit $EXIT_CODE
fi
