#!/usr/bin/env bash
echo "*******************************"
echo   "Running git pre-commit"
echo "*******************************"
OUTPUT="/tmp/pre-commit-check-$(date +%s)"
./gradlew build > $OUTPUT
EXIT_CODE=$?
if [ $EXIT_CODE -ne 1 ]; then
  cat $OUTPUT
  rm $OUTPUT
  echo "***********************************************"
  echo " Please fix the above issues before committing "
  echo "***********************************************"
  exit $EXIT_CODE
fi
