name: Release Ci

on:
  pull_request:
    branches: [ "release" ]

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: run unit test
      run: ./gradlew testGmsDebugUnitTest

  detekt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: run detekt
        run: ./gradlew detektRun


  build_apk_aab:
    name: Build release artifacts
    runs-on: ubuntu-20.04
    steps:

      - uses: actions/checkout@v2

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: build release artifacts
        run: |
          ./gradlew assembleRelease
          ./gradlew bundleRelease

      - name: Upload signed APK
        uses: actions/upload-artifact@v2
        with:
          name: vauma.apk
          path: vauma/build/outputs/apk/release/vauma.apk

      - name: Upload AAB Bundle
        uses: actions/upload-artifact@v2
        with:
          name: vauma.aab
          path: vauma/build/outputs/bundle/release/vauma.aab