name: Release Ci

on:
  pull_request:
    branches: [ "release" ]

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: run unit test
      run: ./gradlew testGmsDebugUnitTest

  detekt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: run detekt
        run: ./gradlew detektRun

  print-modules-graph:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: print module graph
        run: ./gradlew projectDependencyGraph

      - name: Commmit modules dependency praph
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git diff --quiet && git diff --staged --quiet || git commit -am 'Update dependency graph'
      - name: Push modules dependency praph
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}

